version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  kinesis:
    build: .
    volumes:
      - ./src:/code
      - ../neochi-core/src/neochi:/code/neochi
    depends_on:
      - redis
