version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  kinesis:
    build:
      context: .
      dockerfile: ./Dockerfile-x64
    volumes:
      - ./src:/code
      - ../neochi-core/src/neochi:/code/neochi
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
